//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.03 at 01:44:26 AM WAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com.guide/soap/server", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package guide.com.soap.server;
