//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.03 at 01:44:26 AM WAT 
//


package guide.com.soap.server;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StatusId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TxRefId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrigBalance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DestBalance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrigMsisdn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DestMsisdn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="responseCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="responseMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="seqtxRefdId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="seqstatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lasseq" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "statusId",
    "txRefId",
    "origBalance",
    "destBalance",
    "origMsisdn",
    "destMsisdn",
    "responseCode",
    "responseMessage",
    "seqtxRefdId",
    "seqstatus",
    "lasseq"
})
@XmlRootElement(name = "vendResponse")
public class VendResponse {

    @XmlElement(name = "StatusId", required = true)
    protected String statusId;
    @XmlElement(name = "TxRefId", required = true)
    protected String txRefId;
    @XmlElement(name = "OrigBalance", required = true)
    protected String origBalance;
    @XmlElement(name = "DestBalance", required = true)
    protected String destBalance;
    @XmlElement(name = "OrigMsisdn", required = true)
    protected String origMsisdn;
    @XmlElement(name = "DestMsisdn", required = true)
    protected String destMsisdn;
    @XmlElement(required = true)
    protected String responseCode;
    @XmlElement(required = true)
    protected String responseMessage;
    protected String seqtxRefdId;
    protected String seqstatus;
    protected String lasseq;

    /**
     * Gets the value of the statusId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusId() {
        return statusId;
    }

    /**
     * Sets the value of the statusId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusId(String value) {
        this.statusId = value;
    }

    /**
     * Gets the value of the txRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxRefId() {
        return txRefId;
    }

    /**
     * Sets the value of the txRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxRefId(String value) {
        this.txRefId = value;
    }

    /**
     * Gets the value of the origBalance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigBalance() {
        return origBalance;
    }

    /**
     * Sets the value of the origBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigBalance(String value) {
        this.origBalance = value;
    }

    /**
     * Gets the value of the destBalance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestBalance() {
        return destBalance;
    }

    /**
     * Sets the value of the destBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestBalance(String value) {
        this.destBalance = value;
    }

    /**
     * Gets the value of the origMsisdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigMsisdn() {
        return origMsisdn;
    }

    /**
     * Sets the value of the origMsisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigMsisdn(String value) {
        this.origMsisdn = value;
    }

    /**
     * Gets the value of the destMsisdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestMsisdn() {
        return destMsisdn;
    }

    /**
     * Sets the value of the destMsisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestMsisdn(String value) {
        this.destMsisdn = value;
    }

    /**
     * Gets the value of the responseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseCode() {
        return responseCode;
    }

    /**
     * Sets the value of the responseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseCode(String value) {
        this.responseCode = value;
    }

    /**
     * Gets the value of the responseMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseMessage() {
        return responseMessage;
    }

    /**
     * Sets the value of the responseMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseMessage(String value) {
        this.responseMessage = value;
    }

    /**
     * Gets the value of the seqtxRefdId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeqtxRefdId() {
        return seqtxRefdId;
    }

    /**
     * Sets the value of the seqtxRefdId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeqtxRefdId(String value) {
        this.seqtxRefdId = value;
    }

    /**
     * Gets the value of the seqstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeqstatus() {
        return seqstatus;
    }

    /**
     * Sets the value of the seqstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeqstatus(String value) {
        this.seqstatus = value;
    }

    /**
     * Gets the value of the lasseq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLasseq() {
        return lasseq;
    }

    /**
     * Sets the value of the lasseq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLasseq(String value) {
        this.lasseq = value;
    }

}
